spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.159.214:3306/ccfsxu?useUnicode=true&characterEncoding=utf-8
    username: cn
    password: cheng521
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml