server:
  port: 8080
  context-path: /ccfsxu
spring:
  datasource:
    url: jdbc:mysql://goldlone.cn:3306/ccfsxu?useUnicode=true&characterEncoding=utf-8
    username: cn
    password: cheng521
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
#    prefix: /templates/
#    suffix: .html
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    cn:
      goldlone:
        mapper: DEBUG